### ISSUE TITLE
Add command named "community" and get number of registered users

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/nlp-sandbox-client#16]
- [x] Add the command "community" to get information about the community
  - An alternative name could be "analytics", but for now "community" has a more positive spin. It depends on the future actions that will be added to this command.
- [x] Get the number of Synapse users in the Synapse Team "NLP Sandbox Participants" (`Team:3413388`)

**Comment by thomasyu888** [comment]
Number fo users in Synapse team:

```
import synapseclient
syn = synapseclient.login()
syn.restGET("/teamMembers/count/3413388")
```
