### ISSUE TITLE
Why do we have different folders per module?

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/nlp-sandbox-client#23]
We can just put the `evaluations.py` in `nlpsandboxclient` folder.  It is confusing because we have:

```from nlpsandboxclient.evaluation import evaluation```, but the true path is

```
import nlpsandboxclient.evaluation.evaluation
```

Which seems redundant.  There is no reason to really create folder hierarchies as nothing in python is really "private".  Unless we were trying to signal to users that these are sets of "core" functions that will be changed overtime (use at your own risk)

**Comment by tschaffter** [comment]
Thanks for asking! My experience working with Python is limited and I didn't remember what's the best way to structure the code. I don't like either `import nlpsandboxclient.evaluation.evaluation`. Feel free to reorganize the code to whatever makes sense to you.

The only thing I liked about my code is the separation of the CLI from the business logic of the client, which may justify to keep the CLI code in a separate folder.
